import { _electron as electron, expect, test, type Page } from '@playwright/test'
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync, readdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'

const shots = resolve(process.env.MULTIMINE_SHOTS ?? 'test-results/shots')
mkdirSync(shots, { recursive: true })
const shot = (page: Page, name: string) => page.screenshot({ path: join(shots, `${name}.png`) })

test('the workstation runs end to end on mock agents', async () => {
  const root = mkdtempSync(join(tmpdir(), 'mm-e2e-'))
  const project = join(root, 'my-mod')
  mkdirSync(project)
  writeFileSync(join(project, 'README.md'), '# My Minecraft mod\n')
  // enough for the UI Sketcher to know a NeoForge mod when it sees one
  writeFileSync(join(project, 'build.gradle'), "plugins { id 'net.neoforged.moddev' version '2.0.0' }\n")
  const app = await electron.launch({
    // SwiftShader: CI machines have no GPU, and the space scene is WebGL
    args: [resolve('out/main/index.js'), '--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--project', project],
    env: { ...process.env, MULTIMINE_USER_DATA: join(root, 'user'), MULTIMINE_FORCE_MOCK: '1', MULTIMINE_MOCK_DELAY: '25' }
  })
  const page = await app.firstWindow()
  await page.setViewportSize({ width: 1480, height: 900 })
  await expect(page.getByTestId('session-menu')).toBeVisible({ timeout: 20_000 })

  // first run: only Mastermind exists, so the wizard offers a team
  await expect(page.getByTestId('team-wizard')).toBeVisible()
  await page.getByTestId('wizard-all-provider').selectOption('mock')
  await page.waitForTimeout(800)
  await shot(page, '01-team-wizard')
  await page.getByTestId('wizard-create').click()
  await expect(page.getByTestId('team-wizard')).toHaveCount(0, { timeout: 15_000 })
  for (const id of ['planner', 'implementer', 'designer', 'brainstormer', 'context-handler']) expect(existsSync(join(project, '.multimine', 'agents', `${id}.md`))).toBe(true)
  expect(readFileSync(join(project, '.multimine', 'agents', 'implementer.md'), 'utf8')).toContain('gated: true')

  // a custom agent through the editor
  await page.getByTestId('add-agent').click()
  await page.getByTestId('agent-name').fill('Lore Keeper')
  await page.getByTitle('Mock (offline demo)').click()
  await page.waitForTimeout(400)
  await shot(page, '02-agent-editor')
  await page.getByTestId('agent-save').click()
  await expect(page.getByTestId('agent-save')).toHaveCount(0)
  await page.locator('[data-chat-dock] button:has(svg.lucide-x)').first().click()
  await page.waitForTimeout(1500)
  await shot(page, '03-team')

  await page.getByTestId('open-mastermind').click()
  const chat = page.getByTestId('chat-mastermind')
  const input = chat.getByTestId('chat-input')
  await input.fill('Hello Mastermind, plan some stronger magic attacks.')
  await input.press('Enter')
  await expect(chat).toContainText('no AI attached', { timeout: 15_000 })
  await expect(chat.getByTestId('chat-send')).toBeVisible()

  // economy on: a light handoff runs the designer on a cheaper setting for that task, shown with a bolt
  await page.getByTestId('economy').click()
  await expect(page.getByTestId('economy')).toContainText('ON')
  // drive the bus by hand: the mock calls the real tool for a /tool line
  await input.fill('/tool delegate {"agent":"designer","task":"Sketch a stronger attack","difficulty":"light"}')
  await input.press('Enter')
  await page.waitForTimeout(600)
  await shot(page, '04-delegation-in-flight')
  await expect(chat).toContainText('Designer replied', { timeout: 15_000 }).catch(() => undefined)

  await input.fill('/tool ask_user {"questions":[{"question":"Which element should the new attack use?","header":"Element","options":[{"label":"Void","description":"Reality-tearing damage"},{"label":"Fire"},{"label":"Lightning"}]}]}')
  await input.press('Enter')
  await expect(page.getByTestId('inbox').locator('span').first()).toHaveText('1', { timeout: 10_000 })
  await page.waitForTimeout(800)
  await shot(page, '05-brain-waiting')
  await page.getByTestId('inbox').click()
  await page.waitForTimeout(500)
  await shot(page, '06-inbox-question')
  await page.getByRole('button', { name: /^Void/ }).click()
  await page.getByTestId('inbox-submit').click()
  await expect(chat).toContainText('Void', { timeout: 10_000 })
  await page.getByTestId('inbox').click()

  // a push always asks, as a balloon over the agent, answered in the space view itself
  await page.locator('[data-chat-dock] button:has(svg.lucide-x)').first().click()
  await page.evaluate(() => (globalThis as any).mm.api.send('implementer', '/tool request_permission {"action":"git push origin main"}'))
  await expect(page.getByTestId('balloon-implementer')).toBeVisible({ timeout: 10_000 })
  await page.waitForTimeout(500)
  await shot(page, '07-permission-balloon')
  await page.getByTestId('balloon-allow').click()
  await expect(page.getByTestId('balloon-implementer')).toHaveCount(0)

  await page.getByTestId('git').click()
  await page.getByRole('button', { name: 'Initialise git here' }).click()
  await expect(page.getByTestId('git-stage-all')).toBeVisible({ timeout: 10_000 })
  await page.getByText('README.md').first().click()
  await page.waitForTimeout(500)
  await shot(page, '08-git-panel')
  await page.getByTestId('git').click()

  // the code window: find a file, edit and save it, then a terminal and a Claude Code session on the team
  await page.getByTestId('code').click()
  await expect(page.getByTestId('ide')).toBeVisible({ timeout: 20_000 })
  await page.getByTestId('ide-search').fill('readme')
  await page.getByTestId('ide-hit').first().click()
  await expect(page.locator('.monaco-editor').first()).toBeVisible({ timeout: 20_000 })
  await page.locator('.monaco-editor .view-lines').first().click()
  await page.keyboard.press('Control+End')
  await page.keyboard.type('Edited in the Multimine code window.')
  await page.keyboard.press('Control+s')
  await expect.poll(() => readFileSync(join(project, 'README.md'), 'utf8'), { timeout: 10_000 }).toContain('Edited in the Multimine code window.')
  await expect(page.getByTestId('sync-context')).toContainText('(1)', { timeout: 10_000 })
  await page.getByTestId('term-new').click()
  await expect(page.getByTestId('terminal-shell')).toBeVisible()
  await page.waitForTimeout(800)
  await page.getByTestId('terminal-shell').click()
  await page.keyboard.type('echo multimine-$((6*7))')
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('terminal-shell')).toContainText('multimine-42', { timeout: 10_000 })
  await page.evaluate(() => (globalThis as any).mm.api.updateSettings({ claudePath: 'echo' }))
  await page.getByRole('button', { name: 'Claude Code' }).click()
  await expect(page.getByTestId('terminal-claude')).toContainText('--mcp-config', { timeout: 10_000 })
  await page.waitForTimeout(800)
  await shot(page, '09-code-window')
  await page.getByTestId('sync-context').click()
  await page.getByTestId('code').click()
  await page.waitForTimeout(800)
  await shot(page, '10-terminal-agent-orb')

  await page.getByTestId('context').click()
  await page.waitForTimeout(400)
  await shot(page, '11-context-panel')
  await page.getByTestId('context').click()

  // the Tools grid: a plugin is installed off, asks for consent, then runs walled off and talks to the team
  await page.evaluate((dir) => (globalThis as any).mm.api.pluginInstall(dir), resolve('examples/plugins/hello'))
  await page.getByTestId('tools').click()
  await expect(page.getByTestId('tools-grid')).toBeVisible()
  await page.waitForTimeout(500)
  await shot(page, '12-tools-grid')
  await page.getByTestId('tools-edit').click()
  await page.waitForTimeout(200)
  await shot(page, '13-tools-edit')
  await page.getByTestId('tools-edit').click()
  await page.getByTestId('tool-hello').click()
  await expect(page.getByTestId('consent')).toBeVisible()
  await page.waitForTimeout(600)
  await shot(page, '14-consent')
  await page.getByTestId('consent-allow').click()
  const frame = page.frameLocator('[data-testid="plugin-frame-hello"]')
  await expect(frame.locator('#team')).toContainText('Mastermind', { timeout: 10_000 })
  // a new plugin frame runs in its own process and takes input once the compositor has placed it,
  // which under software rendering can be a couple of seconds after its page has loaded
  await expect(async () => {
    await frame.locator('#send').click()
    await expect(frame.locator('#out')).toHaveText('Sent.', { timeout: 1000 })
  }).toPass({ timeout: 15_000 })
  await page.waitForTimeout(400)
  await shot(page, '15-hello-plugin')
  // revoked, the same call is refused inside the plugin
  await page.evaluate(() => (globalThis as any).mm.api.pluginRevoke('hello', 'agents:message'))
  await frame.locator('#send').click()
  await expect(frame.locator('#out')).toContainText('agents:message')
  await page.getByTestId('toolwin-hello').getByTitle('Close').click()

  // the UI Sketcher: a Minecraft GUI drawn on the starter container, exported, sent, then marked up
  await page.getByTestId('tools').click()
  await page.getByTestId('tool-ui-sketcher').click()
  await expect(page.getByTestId('sketcher')).toBeVisible()
  await page.getByTestId('sk-name').fill('Mana Furnace')
  await page.getByTestId('sk-layers').getByText('Container', { exact: true }).click()
  const wb = (await page.getByTestId('sketch-selection').first().boundingBox())!
  const at = (fx: number, fy: number) => [wb.x + wb.width * fx, wb.y + wb.height * fy] as const
  await page.getByTestId('sk-tool-button').click()
  await page.mouse.move(...at(0.56, 0.12))
  await page.mouse.down()
  await page.mouse.move(...at(0.75, 0.2), { steps: 4 })
  await page.mouse.move(...at(0.92, 0.25), { steps: 4 })
  await page.mouse.up()
  await page.getByTestId('sk-prop-text').fill('Smelt')
  await page.getByTestId('sk-tool-slot').click()
  await page.mouse.click(...at(0.2, 0.2))
  await page.getByTestId('sk-tool-progress').click()
  await page.mouse.click(...at(0.36, 0.23))
  await page.getByTestId('sk-prop-notes').fill('Fills as mana is smelted.')
  await page.waitForTimeout(300)
  await shot(page, '18-sketcher')
  await page.getByTestId('sk-look-styled').click()
  await page.mouse.click(...at(0.5, 0.33)) // select the container, to show its handles over the styled look
  await page.waitForTimeout(300)
  await shot(page, '19-sketcher-minecraft')
  await page.getByTestId('sk-tab-mockup').click()
  await expect(page.getByAltText('Mockup')).toBeVisible()
  await expect(page.getByTestId('sk-size')).toHaveCount(4)
  await page.waitForTimeout(300)
  await shot(page, '20-sketch-mockup')
  await page.getByTestId('sk-tab-design').click()
  await page.getByTestId('sk-send').click()
  await page.getByTestId('sk-send-note').fill('Opens from the mana furnace block.')
  await page.getByTestId('sk-send-go').click()
  const sketchDir = join(project, '.multimine', 'sketches', 'mana-furnace')
  await expect.poll(() => existsSync(join(sketchDir, 'mockup.png')), { timeout: 10_000 }).toBe(true)
  const saved = JSON.parse(readFileSync(join(sketchDir, 'sketch.json'), 'utf8'))
  expect(JSON.stringify(saved.tree)).toContain('"text":"Smelt"')
  expect(JSON.stringify(saved.tree)).toContain('Player inventory')
  expect(existsSync(join(sketchDir, 'sketch.png'))).toBe(true)
  const busText = () => {
    const sessions = join(project, '.multimine', 'sessions')
    return readdirSync(sessions).map((d) => (existsSync(join(sessions, d, 'bus.jsonl')) ? readFileSync(join(sessions, d, 'bus.jsonl'), 'utf8') : '')).join('\n')
  }
  await expect.poll(busText, { timeout: 10_000 }).toContain('plugin:ui-sketcher')
  expect(busText()).toContain('Mana Furnace')
  // the mockup went to the gallery; mark it up and send it back as a revision
  await page.getByTestId('sk-tab-revisions').click()
  await page.getByTestId('sk-shot').first().click()
  const mk = (await page.getByTestId('sk-markup-svg').boundingBox())!
  await page.mouse.move(mk.x + mk.width * 0.55, mk.y + mk.height * 0.2)
  await page.mouse.down()
  await page.mouse.move(mk.x + mk.width * 0.75, mk.y + mk.height * 0.35, { steps: 5 })
  await page.mouse.up()
  await page.getByTestId('sk-revision-notes').fill('Make the Smelt button narrower.')
  await page.waitForTimeout(300)
  await shot(page, '21-sketch-revision')
  await page.getByTestId('sk-revision-send').click()
  await expect.poll(() => existsSync(join(sketchDir, 'revision-1.png')), { timeout: 10_000 }).toBe(true)

  // a Godot HUD: game elements anchored where they are drawn, previewed on every screen, briefed for Godot
  await page.getByTestId('sk-tab-design').click()
  await page.getByTestId('sk-new').click()
  await page.getByTestId('sk-preset-godot').click()
  await page.getByTestId('sk-name').fill('Combat HUD')
  const cv = (await page.getByTestId('sketch-canvas').boundingBox())!
  const z = Math.min((cv.width - 48) / 1920, (cv.height - 48) / 1080)
  const hud = (ux: number, uy: number) => [cv.x + (cv.width - 1920 * z) / 2 + ux * z, cv.y + (cv.height - 1080 * z) / 2 + uy * z] as const
  await page.getByTestId('sk-tool-bar').click()
  await page.mouse.move(...hud(48, 992))
  await page.mouse.down()
  await page.mouse.move(...hud(240, 1010), { steps: 4 })
  await page.mouse.move(...hud(424, 1024), { steps: 4 })
  await page.mouse.up()
  await page.getByTestId('sk-prop-name').fill('Health')
  await page.getByTestId('sk-tool-bar').click()
  await page.mouse.move(...hud(48, 944))
  await page.mouse.down()
  await page.mouse.move(...hud(424, 968), { steps: 6 })
  await page.mouse.up()
  await page.getByTestId('sk-prop-name').fill('Mana')
  for (const [i, key] of ['Q', 'E', 'R'].entries()) {
    await page.getByTestId('sk-tool-ability').click()
    await page.mouse.click(...hud(832 + i * 96, 960))
    await page.getByTestId('sk-prop-text').fill(key)
  }
  await page.getByTestId('sk-prop-value').fill('0.4')
  await page.getByTestId('sk-tool-minimap').click()
  await page.mouse.click(...hud(1640, 48))
  await page.getByTestId('sk-tool-crosshair').click()
  await page.mouse.click(...hud(936, 516))
  await page.getByTestId('sk-tool-dialogue').click()
  await page.mouse.click(...hud(410, 680))
  await page.getByTestId('sk-tool-toast').click()
  await page.mouse.click(...hud(1456, 600))
  await page.getByTestId('sk-look-styled').click()
  await page.keyboard.press('Escape')
  await page.waitForTimeout(400)
  await shot(page, '22-godot-hud')
  await page.getByTestId('sk-tab-mockup').click()
  await expect(page.getByTestId('sk-size')).toHaveCount(6)
  await page.getByTestId('sk-size').nth(3).click()
  await page.waitForTimeout(400)
  await shot(page, '23-godot-sizes')
  await page.getByTestId('sk-send').click()
  await page.getByTestId('sk-send-go').click()
  const hudDir = join(project, '.multimine', 'sketches', 'combat-hud')
  await expect.poll(() => existsSync(join(hudDir, 'sketch.json')), { timeout: 10_000 }).toBe(true)
  const hudJson = JSON.parse(readFileSync(join(hudDir, 'sketch.json'), 'utf8'))
  expect(hudJson).toMatchObject({ target: 'godot', engine: 'Godot' })
  expect(JSON.stringify(hudJson.tree)).toContain('"anchor":"top-right"')
  await expect.poll(busText, { timeout: 10_000 }).toContain('Combat HUD')
  await page.getByTestId('toolwin-ui-sketcher').getByTitle('Close').click()

  // a fallback chain in the agent editor
  await page.getByTestId('add-agent').click()
  await page.getByTestId('agent-name').fill('Fallback Demo')
  await page.getByTestId('agent-fallback-add').click()
  await page.getByTestId('agent-fallback-add').click()
  await page.getByTestId('agent-fallback').scrollIntoViewIfNeeded()
  await page.waitForTimeout(300)
  await shot(page, '24-fallback-chain')
  await page.keyboard.press('Escape')

  await page.getByTestId('settings').click()
  await page.waitForTimeout(800)
  await shot(page, '25-settings')
  await page.keyboard.press('Escape')

  expect(existsSync(join(project, '.multimine', 'sessions'))).toBe(true)
  expect(existsSync(join(project, 'multimine.md'))).toBe(true)
  await app.close()
})
